// Devtest harness seed: builds a simple two-step PIA (Privacy Impact Assessment)
// flow from the repo's test fixtures by driving the SAME container use cases and
// services the product's own endpoints use — no product code is changed, this is
// pure configuration of a running system.
//
//   Step 1 (conversational): gather the project/system details an assessor needs.
//   Step 2 (generate_document): produce the PIA using `pia-tool.docx` as the
//           docx template, grounded in the privacy-impact-assessment guide PDF
//           ingested as a flow RAG context doc.
//
// Run as a one-shot compose service against the devtest stack (postgres + storage
// + migrate up). Idempotent: a second run with the flow already present is a noop.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Result } from "@rbrasier/domain";
import { DocxGenerator } from "@rbrasier/adapters";
import { getContainer, type Container } from "../src/lib/container";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const fixturesDir = process.env.PIA_FIXTURES_DIR ?? join(repoRoot, "tests", "e2e", "fixtures");

// Tagged derivative of pia-tool.docx — the same document with {{placeholder}}
// tags injected after each body section heading (generated by
// apps/web/scripts/tag-pia-template.cjs), since generate_document needs tags to
// know what the AI should fill.
const TEMPLATE_FILE = "pia-tool.tagged.docx";
const GUIDE_FILE = "guide-to-undertaking-privacy-impact-assessments.pdf";
const DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
const PDF_MIME = "application/pdf";

const FLOW_NAME = "PIA — Privacy Impact Assessment";

const GENERATE_INSTRUCTION =
  "Using the details gathered and the privacy-impact-assessment guide, fill in the PIA tool template — describing the information flows, assessing privacy risks, and recommending mitigations.";
const GENERATE_DONE_WHEN =
  "The PIA report is generated from the template with every section completed.";

const docxGenerator = new DocxGenerator();

const unwrap = <T>(result: Result<T>, context: string): T => {
  if (result.error) throw new Error(`${context}: ${result.error.message}`);
  return result.data;
};

const safeFilename = (name: string): string => name.replace(/[^a-zA-Z0-9._-]/g, "_");
const stamp = (): string => new Date().toISOString().replace(/[:.]/g, "-");

const resolveAdminUserId = async (container: Container): Promise<string> => {
  const email = process.env.ADMIN_SEED_EMAIL ?? "admin@example.com";
  const existing = unwrap(await container.repos.users.findByEmail(email), "find admin user");
  if (existing) return existing.id;
  const created = unwrap(
    await container.repos.users.create({ email, isAdmin: true }),
    "create admin user",
  );
  return created.id;
};

const alreadySeeded = async (container: Container, ownerUserId: string): Promise<boolean> => {
  const flows = unwrap(await container.useCases.listFlows.execute(), "list flows");
  return flows.some((flow) => flow.name === FLOW_NAME && flow.ownerUserId === ownerUserId);
};

// Mirrors apps/web/.../nodes/[nodeId]/template POST: extract tags + fields + full
// text, summarise to the structural skeleton, store the docx, write the template
// reference into the generate_document node config, then index its prose for RAG.
const attachTemplate = async (
  container: Container,
  flowId: string,
  nodeId: string,
  baseConfig: Record<string, unknown>,
): Promise<void> => {
  const buffer = readFileSync(join(fixturesDir, TEMPLATE_FILE));

  const tags = unwrap(
    docxGenerator.extractTags({ templateBytes: buffer }),
    "extract template tags",
  ).tags;
  if (tags.length === 0) {
    throw new Error(
      `${TEMPLATE_FILE} has no {{ tag }} placeholders — it cannot drive a generate_document step.`,
    );
  }

  const fields = unwrap(
    docxGenerator.extractFields({ templateBytes: buffer }),
    "extract template fields",
  ).fields;
  const documentTemplateContent = unwrap(
    docxGenerator.extractFullText({ templateBytes: buffer }),
    "extract template text",
  ).text;

  const storageKey = `templates/${nodeId}/${stamp()}-${safeFilename(TEMPLATE_FILE)}`;
  unwrap(await container.objectStorage.put(storageKey, buffer, DOCX_MIME), "store template");

  const summary = unwrap(
    await container.useCases.summariseTemplate.execute({
      fullExtractedText: documentTemplateContent,
      tags,
    }),
    "summarise template",
  );

  unwrap(
    await container.useCases.updateFlowNode.execute(nodeId, {
      config: {
        ...baseConfig,
        documentTemplatePath: storageKey,
        documentTemplateFilename: safeFilename(TEMPLATE_FILE),
        documentTemplateContent,
        documentTemplateStructuredContent: summary.structuredContent,
        documentTemplateFields: fields,
      },
    }),
    "save template reference",
  );

  const indexResult = await container.services.documentIndexer.indexDocument({
    flowId,
    sessionId: null,
    sourceType: "template",
    storagePath: storageKey,
    filename: safeFilename(TEMPLATE_FILE),
    text: documentTemplateContent,
  });
  if (indexResult.error) {
    console.warn(`  template stored but embedding failed: ${indexResult.error.message}`);
    return;
  }
  console.log(`  template indexed (${indexResult.data.chunkCount} chunks, ${tags.length} tags)`);
};

// Mirrors apps/web/.../flows/[id]/context-docs POST: extract text, store the file,
// record context-doc content, attach it to the flow, and embed it for RAG.
const attachContextDoc = async (container: Container, flowId: string): Promise<void> => {
  const buffer = readFileSync(join(fixturesDir, GUIDE_FILE));

  const extracted = unwrap(
    await container.services.documentExtractor.extract({ buffer, mimeType: PDF_MIME }),
    "extract guide text",
  ).trim();
  if (extracted.length === 0) {
    throw new Error(`${GUIDE_FILE} produced no readable text (scanned PDF needs OCR).`);
  }

  const storageKey = `context/${flowId}/${stamp()}-${safeFilename(GUIDE_FILE)}`;
  unwrap(await container.objectStorage.put(storageKey, buffer, PDF_MIME), "store guide");

  unwrap(
    await container.repos.contextDocContent.upsert({
      flowId,
      storagePath: storageKey,
      extractedText: extracted,
      extractionStatus: "complete",
    }),
    "store guide extracted text",
  );

  unwrap(
    await container.useCases.addContextDoc.execute(flowId, {
      id: crypto.randomUUID(),
      filename: safeFilename(GUIDE_FILE),
      mimeType: PDF_MIME,
      sizeBytes: buffer.byteLength,
      storagePath: storageKey,
      extractedText: extracted,
      extractionStatus: "complete",
    }),
    "attach context doc",
  );

  const indexResult = await container.services.documentIndexer.indexDocument({
    flowId,
    sessionId: null,
    sourceType: "flow_context_doc",
    storagePath: storageKey,
    filename: safeFilename(GUIDE_FILE),
    text: extracted,
  });
  if (indexResult.error) {
    console.warn(`  guide stored but embedding failed: ${indexResult.error.message}`);
    return;
  }
  console.log(`  guide indexed (${indexResult.data.chunkCount} chunks)`);
};

const main = async (): Promise<void> => {
  const container = getContainer();
  const ownerUserId = await resolveAdminUserId(container);

  if (await alreadySeeded(container, ownerUserId)) {
    console.log("PIA flow already present — nothing to do.");
    return;
  }

  console.log("Creating PIA flow...");
  const flow = unwrap(
    await container.useCases.createFlow.execute({
      name: FLOW_NAME,
      description: "Two-step assessment: gather the project details, then draft the PIA report.",
      expertRole: "Privacy Officer",
      ownerUserId,
    }),
    "create PIA flow",
  );

  const gatherNode = unwrap(
    await container.useCases.createFlowNode.execute({
      flowId: flow.id,
      type: "conversational",
      name: "Gather project details",
      positionX: 120,
      positionY: 120,
      config: {
        aiInstruction:
          "Interview the operator about the project or system being assessed: what personal information it collects, why, who it is shared with, how it is stored and secured, and the data flows involved. Use the privacy-impact-assessment guide to decide what to probe for.",
        doneWhen:
          "Enough detail is captured to populate a privacy impact assessment: the information handled, its purpose, the parties involved, and the key data flows.",
        outputType: "conversation_only",
        advanceConfidenceThreshold: 85,
      },
    }),
    "create gather node",
  );

  const documentNode = unwrap(
    await container.useCases.createFlowNode.execute({
      flowId: flow.id,
      type: "conversational",
      name: "Draft PIA report",
      positionX: 460,
      positionY: 120,
      config: {
        aiInstruction: GENERATE_INSTRUCTION,
        doneWhen: GENERATE_DONE_WHEN,
        outputType: "generate_document",
      },
    }),
    "create document node",
  );

  unwrap(
    await container.useCases.createFlowEdge.execute({
      flowId: flow.id,
      fromNodeId: gatherNode.id,
      toNodeId: documentNode.id,
    }),
    "create edge",
  );

  console.log("Attaching PIA tool template...");
  await attachTemplate(container, flow.id, documentNode.id, {
    aiInstruction: GENERATE_INSTRUCTION,
    doneWhen: GENERATE_DONE_WHEN,
    outputType: "generate_document",
  });

  console.log("Ingesting PIA guide as a RAG context doc...");
  await attachContextDoc(container, flow.id);

  console.log("Publishing flow...");
  unwrap(
    await container.useCases.updateFlow.execute(
      flow.id,
      { status: "published", visibility: { kind: "global" } },
      { canPublishToEveryone: true },
    ),
    "publish PIA flow",
  );

  console.log(`Done. PIA flow ${flow.id} published and available to start.`);
};

main()
  .then(() => process.exit(0))
  .catch((cause: unknown) => {
    console.error(`PIA seed failed: ${cause instanceof Error ? cause.message : String(cause)}`);
    process.exit(1);
  });
